version: "3.5"

services:

  traefik:
    image: traefik:v2.2
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      - "--metrics.prometheus.entryPoint=traefik"
    networks:
      - traefik
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2.2.0
    environment:
      - AUTH_HOST=toot.svr.luxair
      - SECRET=mysecret
      #- COOKIE_NAME=iPlanetDirectoryProAcc
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=http://sso1-acc.svr.luxair:8080/opensso/oauth2
      - PROVIDERS_OIDC_CLIENT_ID=toot
      - PROVIDERS_OIDC_CLIENT_SECRET=toot
      - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`toot.svr.luxair`) && PathPrefix(`/_oauth`)"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    networks:
      - traefik

networks:
  traefik:
    name: traefik

